version: '3'
services:
  database:
    build: ./Database
    container_name: database
    restart: always
    ports:
      - 3307:3306
  api:
    build: api
    container_name: api
    ports:
    - "80:80"
  migration:
    build: .
    container_name: migration
    depends_on:
      - database